#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2022 DOKUMENTA AG - License: GNU General Public License v2

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.elphase import *  # pylint: disable=wildcard-import,unused-wildcard-import


def parse_ups_delphys_inphase(info):
    parsed = {}
    for index, stat_name in enumerate(("voltage", "frequency")):
        try:
            parsed[stat_name] = float(info[0][index]) / 10
        except ValueError:
            continue

    return parsed and {"1": parsed}


def inventory_ups_delphys_inphase(parsed):
    if parsed:
        return [("1", {})]


check_info["ups_delphys_inphase"] = {
    "parse_function": parse_ups_delphys_inphase,
    "inventory_function": inventory_ups_delphys_inphase,
    "check_function": check_elphase,
    "service_description": "UPS Input Phase %s",
    "snmp_scan_function": lambda oid: "DELPHYS_GP_2.0" in oid(".1.3.6.1.2.1.1.5.0"),
    "snmp_info": (
        ".1.3.6.1.4.1.4555.1.1.5.1.3",
        [
            "1",  #adicomUpsInputFrequency "Rectifier Input frequency in 0.1 HZ."
            "3.1.2",  #adicomUpsInputVoltage "Rectifier input voltage in volts"
        ]),
    "group": "el_inphase",
}
