#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2022 DOKUMENTA AG - License: GNU General Public License v2

def inventory_ups_delphys_out_source(info):
    if info:
        return [(None, None)]


def check_ups_delphys_out_source(_no_item, _no_params, info):

    ups_delphys_source_states = {
        1: (3, "Standby"),
        2: (2, "none"),
        3: (0, "Normal"),
        4: (1, "Internal Maintenance Bypass"),
        5: (2, "On battery"),
        6: (0, "Booster"),
        7: (0, "Reducer"),
        8: (0, "Standby"),
        9: (0, "Eco mode"),
       10: (0, "E-Saver"),
    }

    return ups_delphys_source_states[int(info[0][0])]


check_info["ups_delphys_out_source"] = {
    "inventory_function": inventory_ups_delphys_out_source,
    "check_function": check_ups_delphys_out_source,
    "service_description": "UPS Output Source",
    "snmp_info": (".1.3.6.1.4.1.4555.1.1.5.1.4", ["1"]),
    "snmp_scan_function": lambda oid: "DELPHYS_GP_2.0" in oid(".1.3.6.1.2.1.1.5.0"),
}