#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2022 DOKUMENTA AG - License: GNU General Public License v2

def inventory_ups_delphys_alarms(info):
    if info:
        return [(None, None)]


def check_ups_delphys_alarms(_no_item, _no_params, info):
    oiddef = {
        "1": (2, "Imminent Stop"),
        "2": (2, "Overload"),
        "3": (2, "Transfer Impossible"),
        "4": (1, "Insufficient Resource"),
        "5": (2, "Redundancy Loss"),
        "6": (2, "Battery temperature Alarm"),
        "7": (2, "general alarm"),
    }

    result = False
    for oidend, flag in info:
        if flag and flag != "NULL" and int(flag):
            result = True
            yield oiddef[oidend]

    if not result:
        yield 0, "No alarms"


check_info["ups_delphys_alarms"] = {
    "inventory_function": inventory_ups_delphys_alarms,
    "check_function": check_ups_delphys_alarms,
    "service_description": "UPS Alarms",
    "snmp_info": (
        ".1.3.6.1.4.1.4555.1.1.5.1.6.1",
        [
            OID_END,
            "7",
        ],
    ),
    "snmp_scan_function": lambda oid: "DELPHYS_GP_2.0" in oid(".1.3.6.1.2.1.1.5.0"),
}