#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2022 DOKUMENTA AG - License: GNU General Public License v2

# NOTE: Careful when replacing the *-import below with a more specific import. This can cause
# problems because it might remove variables from the check-context which are necessary for
# resolving legacy discovery results such as [("SUMMARY", "diskstat_default_levels")]. Furthermore,
# it might also remove variables needed for accessing discovery rulesets.
from cmk.base.check_legacy_includes.elphase import *  # pylint: disable=wildcard-import,unused-wildcard-import

factory_settings["ups_modulys_inphase_default_levels"] = {}


def parse_ups_delphys_inphase(info):
    parsed = {}
    parsed["Phase 1"] = {
        "frequency": int(info[0][1]) / 10.0,
        "voltage": int(info[0][2]) / 10.0,
        "current": int(info[0][3]) / 10.0,
    }

    if info[0][0] == "3":
        parsed["Phase 2"] = {
            "frequency": int(info[0][4]) / 10.0,
            "voltage": int(info[0][5]) / 10.0,
            "current": int(info[0][6]) / 10.0,
        }

        parsed["Phase 3"] = {
            "frequency": int(info[0][7]) / 10.0,
            "voltage": int(info[0][8]) / 10.0,
            "current": int(info[0][9]) / 10.0,
        }

    return parsed


check_info["ups_delphys_inphase"] = {
    "parse_function": parse_ups_delphys_inphase,
    "inventory_function": discover(),
    "check_function": check_elphase,
    "service_description": "UPS Input %s",
    "has_perfdata": True,
    "default_levels_variable": "ups_delphys_inphase_default_levels",
    "group": "el_inphase",
    "snmp_info": (
        ".1.3.6.1.4.1.2254.2.4.4",
        [
            "1",  # dupsInputNumLines
            "2",  # dupsInputFrequency1
            "3",  # dupsInputVoltage1
            "4",  # dupsInputCurrent1
            "5",  # dupsInputFrequency2
            "6",  # dupsInputVoltage2
            "7",  # dupsInputCurrent2
            "8",  # dupsInputFrequency3
            "9",  # dupsInputVoltage3
            "10",  # dupsInputCurrent3
        ],
    ),
    "snmp_scan_function": lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.2254.2.4",
}